name: Deploy to AWS STAGING
on:
  push:
    branches: ["main"]
env:
  AWS_REGION: "ap-southeast-3"
  ECR_REPOSITORY: "975050366595.dkr.ecr.ap-southeast-3.amazonaws.com/doitpay"

jobs:
  deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: latest

        run: |
          # Build a docker container and
          # push it to ECR so that it can be deployed to ECS.
          make ENV=staging SERVICE=web build-container-image
          make ENV=staging SERVICE=web push-container-image

